"""
Configuracion del proyecto Munitramites. >>> ARCHIVO DE CONFIG, NO DE LOGICA <<<

Todo lo de Django vive en UNA sola carpeta, `munitramites/`, que contiene la
configuracion (este archivo, urls.py, wsgi.py) y la app (models, views, …).

Donde tocar cada cosa:

  - Agregar una vista / ruta ......... munitramites/views/, urls.py
  - Agregar una tabla ................ models.py
  - Ver una tabla en el admin ........ admin.py
  - Logica reutilizable .............. munitramites/services/
  - Cambiar la base de datos ......... DATABASES, mas abajo
  - Agregar una app nueva ............ INSTALLED_APPS + manage.py startapp

Orden de este archivo:

   1. Seguridad y hosts          4. Internacionalizacion
   2. Apps y middlewares         5. Archivos estaticos
   3. Base de datos              6. Auth, correo y chatbot

Generated by 'django-admin startproject' using Django 5.2.17.
"""

from pathlib import Path

# BASE_DIR = raiz del repositorio (la que contiene manage.py)
BASE_DIR = Path(__file__).resolve().parent.parent


# ---------------------------------------------------------------------------
# 1. Seguridad
# ---------------------------------------------------------------------------
# WARNING: la clave esta en el repo porque el proyecto es una demo local.
# En produccion se levanta desde el entorno: os.environ['SECRET_KEY'].
SECRET_KEY = 'django-insecure-d$vz@z=g66+6s0ktwy0ws^8lpelguhlupgj%1=8k*w-=eh#(=j'

# WARNING: nunca con DEBUG en produccion.
DEBUG = True

# '*' porque el sitio se abre desde la PC local (localhost) y desde la red
# local (IP de la maquina). Para publicarlo, dejar solo los dominios reales.
ALLOWED_HOSTS = ['*']


# ---------------------------------------------------------------------------
# 2. Apps y middlewares
# ---------------------------------------------------------------------------
INSTALLED_APPS = [
    # Apps de Django
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Este proyecto (una sola carpeta: config + app juntas)
    'munitramites',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'munitramites.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Plantillas de este sitio, declaradas aca para que tengan PRIORIDAD
        # sobre las que traen las apps instaladas. Sin esto, `registration/`
        # se resuelve contra django.contrib.admin (que va primero en
        # INSTALLED_APPS) y nuestras paginas de reset quedarian pisadas.
        # Las plantillas de cada app siguen estando disponibles en segundo
        # lugar por APP_DIRS (por ejemplo todo lo de /admin/).
        'DIRS': [BASE_DIR / 'munitramites' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # Formulario de registro para el modal del header
                'munitramites.context_processors.formularios_modales',
            ],
        },
    },
]

WSGI_APPLICATION = 'munitramites.wsgi.application'


# ---------------------------------------------------------------------------
# 3. Base de datos (Firebird, dentro de Docker)
# ---------------------------------------------------------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django_firebird',  # Paquete django-firebird (usa firebird-driver)
        'NAME': '/var/lib/firebird/data/munitramites.fdb',  # Ruta vista desde el servidor
        'USER': 'SYSDBA',
        'PASSWORD': 'masterkey',
        'HOST': 'firebird',
        'PORT': '3050',
        'OPTIONS': {
            'charset': 'UTF8',
        },
        # Base que usa `manage.py test`. Sin esto, django-firebird arma el
        # nombre como «test_» + la ruta completa y Firebird no puede crearla.
        'TEST': {
            'NAME': '/var/lib/firebird/data/munitramites_test.fdb',
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ---------------------------------------------------------------------------
# 4. Internacionalizacion
# ---------------------------------------------------------------------------
LANGUAGE_CODE = 'es-ar'

# Argentina (Misiones)
TIME_ZONE = 'America/Argentina/Buenos_Aires'

USE_I18N = True

USE_TZ = True


# ---------------------------------------------------------------------------
# 5. Archivos estaticos
# ---------------------------------------------------------------------------
STATIC_URL = '/static/'

# Carpeta de estilos, imagenes y JS del sitio (fuera de las apps)
STATICFILES_DIRS = [BASE_DIR / 'static']


# ---------------------------------------------------------------------------
# 6. Autenticacion, correo y chatbot
# ---------------------------------------------------------------------------

# El admin nativo de Django usa su propio login (/admin/login/).
# LOGIN_URL es para las paginas de ciudadanos (/consultas, /perfil, …).
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# --- Correo (RF-15: restablecer la clave) ----------------------------------
# No hay servidor SMTP en el entorno de desarrollo: los mails salen por la
# consola, o sea que el link de restablecimiento aparece en:
#
#     docker compose logs web
#
# Para produccion, cambiar por el backend que corresponda (SMTP, SendGrid, …)
# y definir EMAIL_HOST / EMAIL_PORT / EMAIL_HOST_USER / EMAIL_HOST_PASSWORD.
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'no-responder@munitramites.test'

# --- Chatbot (asistente con arquitectura RAG) ------------------------------
# `services/chatbot/` implementa indexacion -> recuperacion -> generacion.
#
# CHATBOT_LLM es la CONEXION con el modelo de lenguaje. Mientras el
# proveedor este vacio, el pipeline responde con la plantilla anclada al
# contexto recuperado (sin alucinar: si no hay fragmentos relevantes, lo
# dice).
#
# Hoy el asistente redacta con Qwen (modelo ligero) corriendo EN LOCAL,
# dentro de Docker, para no depender de internet ni de una API key:
#
#     servicio `ollama` de docker-compose.yml
#         -> imagen propia `Dockerfile.ollama`
#            (Ollama + qwen2.5:1.5b ya descargados adentro,
#             se exporta con `docker save`)
#
# Adentro de la red de compose el host se llama `ollama`. Si algun dia el
# sitio corre en la PC host (fuera de Docker), cambiarlo a
# `http://localhost:11434/v1`, que es donde se publica ese puerto.
#
# Si el contenedor esta apagado, el modelo no llega a responder dentro de
# `timeout` o falla la red, la respuesta cae en la plantilla local: la
# conversacion nunca se rompe.
CHATBOT_LLM = {
    # 'ollama' (local, sin clave) | openai | anthropic | gemini | custom
    'proveedor': 'ollama',
    # Solo la piden los proveedores de la nube; Ollama trabaja sin clave.
    'api_key': '',
    # Modelos disponibles: docker compose exec ollama ollama list
    'modelo': 'qwen2.5:1.5b',
    # URL interna del servicio `ollama` (dialecto OpenAI de Ollama).
    'base_url': 'http://ollama:11434/v1',
    # La PC no tiene GPU: en CPU una respuesta lleva unos segundos.
    'timeout': 60,
}

# Fragmentos que se recuperan por consulta y se pasan como contexto al LLM.
CHATBOT_TOP_K = 4
# Puntaje minimo para considerar que un fragmento responde la pregunta.
# Por debajo, el asistente responde que no dispone de esa informacion.
# Con BM25 el puntaje depende de cuantos fragmentos indexados haya: con
# pocos, el IDF es chico y un 1.0 es imposible de alcanzar. 0.5 sigue
# descartando las consultas sin coincidencia (esas puntuan 0).
CHATBOT_UMBRAL = 0.5


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
