# Generated by Django 5.2.17 on 2026-09-28 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Organismo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('direccion', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Organismo',
                'verbose_name_plural': 'Organismos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Tramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tema', models.CharField(choices=[('Documentacion', 'Documentación'), ('Transito', 'Tránsito'), ('Comercio', 'Comercio'), ('Seguridad', 'Seguridad'), ('Salud', 'Salud'), ('Impuestos', 'Impuestos'), ('Vivienda', 'Vivienda')], max_length=20)),
                ('modalidad', models.CharField(choices=[('presencial', 'Presencial'), ('virtual', 'Virtual'), ('mixta', 'Mixta')], max_length=20)),
                ('descripcion', models.TextField()),
                ('enlace_turnos', models.URLField(blank=True, default='')),
                ('enlace_oficial', models.URLField(blank=True, default='')),
                ('destacado', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tramites', to='munitramites.municipio')),
                ('organismo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tramites', to='munitramites.organismo')),
            ],
            options={
                'verbose_name': 'Trámite',
                'verbose_name_plural': 'Trámites',
                'ordering': ['-destacado', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('consulta', 'Consulta'), ('sugerencia', 'Sugerencia'), ('reclamo', 'Reclamo')], default='consulta', max_length=20)),
                ('asunto', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('respondido', 'Respondido'), ('cerrado', 'Cerrado')], default='pendiente', max_length=20)),
                ('respuesta', models.TextField(blank=True, default='')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas', to=settings.AUTH_USER_MODEL)),
                ('tramite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas', to='munitramites.tramite')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Requisito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=300)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitos', to='munitramites.tramite')),
            ],
            options={
                'verbose_name': 'Requisito',
                'verbose_name_plural': 'Requisitos',
                'ordering': ['orden', 'id'],
                'unique_together': {('tramite', 'orden')},
            },
        ),
    ]
