# Generated by Django 5.2.17 on 2026-09-28 23:28

import django.db.models.deletion
from django.db import migrations, models


def copiar_enlaces_viejos(apps, schema_editor):
    """Pasa los campos viejos (enlace_turnos / enlace_oficial) a botones.

    Así la ficha sigue mostrando los enlaces con nombre de botón aunque el
    admin todavía no haya cargado ninguno. Idempotente: no duplica.
    """
    Tramite = apps.get_model('munitramites', 'Tramite')
    Enlace = apps.get_model('munitramites', 'Enlace')

    for tramite in Tramite.objects.all():
        existentes = {e.url for e in tramite.enlaces.all()}
        if tramite.enlace_turnos and tramite.enlace_turnos not in existentes:
            Enlace.objects.create(
                tramite=tramite, nombre='Pedir turno',
                url=tramite.enlace_turnos, orden=1,
            )
        if tramite.enlace_oficial and tramite.enlace_oficial not in existentes:
            Enlace.objects.create(
                tramite=tramite, nombre='Sitio del organismo',
                url=tramite.enlace_oficial, orden=2,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('munitramites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Texto del boton, ej.: «Pedir turno» o «Sitio del organismo».', max_length=100)),
                ('url', models.URLField(help_text='URL completa, ej.: https://ejemplo.gob.ar/…')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enlaces', to='munitramites.tramite')),
            ],
            options={
                'verbose_name': 'Enlace oficial',
                'verbose_name_plural': 'Enlaces oficiales',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.RunPython(copiar_enlaces_viejos, migrations.RunPython.noop),
    ]
