# Generated by Django 5.2.17 on 2026-10-02 17:44
"""Tema pasa de `choices` fijo en el modelo a tabla propia (fila en el admin).

Firebird no admite convertir una columna VARCHAR a INTEGER en el lugar
(«Cannot change datatype from a character type to a non-character type»),
así que la migración recrea la columna: borra la `tema` vieja y agrega
`tema_id` con la clave foránea. La tabla de trámites estaba vacía en este
punto del proyecto, así que no hay datos que perder. Al final siembra los
7 temas que antes eran las opciones del combo.
"""

import django.db.models.deletion
from django.db import migrations, models


def sembrar_temas(apps, schema_editor):
    """Los 7 temas originales (antes: `Tramite.Tema`)."""
    Tema = apps.get_model('munitramites', 'Tema')
    for nombre in (
        'Documentación', 'Tránsito', 'Comercio', 'Seguridad',
        'Salud', 'Impuestos', 'Vivienda',
    ):
        Tema.objects.get_or_create(nombre=nombre)


class Migration(migrations.Migration):

    dependencies = [
        ('munitramites', '0003_organismo_ocupacion_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True)),
            ],
            options={
                'verbose_name': 'Tema',
                'verbose_name_plural': 'Temas',
                'ordering': ['nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='tramite',
            name='tema',
        ),
        migrations.AddField(
            model_name='tramite',
            name='tema',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='tramites',
                to='munitramites.tema',
            ),
        ),
        migrations.RunPython(sembrar_temas, migrations.RunPython.noop),
    ]
